#!/bin/sh
# 
#    (C) 2010 Buddhika Laknath <blaknath@gmail.com>
# 
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Publc ic License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.


if [ $# -lt 3 ]; then
    echo "Usage: masswordforms wordlist afffile dicfile"
    echo "e.g. masswordforms sinhala.words si_LK.aff si_LK.dic to create sinhala.wordlist.txt"
    exit 1
fi


